name: Stick-Translate
on:
  push:
    paths:
      - 'res/values/string.xml'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashishb/android-auto-translate@master
        with:
          args: es
      - name: Save
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stick-Bot"
          git add .
          git commit -m "Traducci√≥n completada para Stick" || exit 0
          git push
