name: Auto Translate Strings

on:
  push:
    paths:
      - 'res/values/strings.xml' # Se activa cuando subes este archivo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Android Auto Translate
        uses: ashishb/android-auto-translate@master
        with:
          # Esto le dice que use Google Translate para crear el archivo en español
          languages: es 

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Traducción automática de Stick" || exit 0
          git push
