name: Stick-Translate
on:
  workflow_dispatch: # Permite el encendido manual que GitHub recomienda para móvil

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Versión más reciente y estable

      - name: Auto Translate
        uses: ashishb/android-auto-translate@master
        with:
          args: es # Comando oficial para traducir al español

      - name: Commit and Push
        run: |
          git config --local user.email "stick-bot@github.com"
          git config --local user.name "Stick-Bot"
          git add .
          git commit -m "Stick: Traducción profesional completada" || exit 0
          git push
